services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: devpigh_admin
      POSTGRES_PASSWORD: fatmanpiggy
      POSTGRES_DB: devpigh
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devpigh_admin -d devpigh"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
